####
#子分区
###
#创建表 ts
#——》子分区，适于保存非常大量的数据
DROP TABLE IF EXISTS ts;
CREATE TABLE ts(
	id INT,
	purchased DATE
)
PARTITION BY RANGE(YEAR(purchased))
SUBPARTITION BY HASH(TO_DAYS(purchased))
SUBPARTITIONS 2
(
	PARTITION P0 VALUES LESS THAN (1990),
	PARTITION P1 VALUES LESS THAN (2000),
	PARTITION P2 VALUES LESS THAN (MAXVALUE)
);

#查询表 ts
SELECT * FROM ts;