####
#创建指定存储引擎的新表
###

#创建使用 MyISAM 存储引擎的表 ai
CREATE TABLE ai(
	i BIGINT(20) NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(i)
) ENGINE=MyISAM DEFAULT CHARSET=gbk;


#创建使用 InnoDB 存储引擎的表 country
CREATE TABLE country(
 country_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
 country VARCHAR(50) NOT NULL,
 last_update TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY(country_id)
)ENGINE=InnoDB DEFAULT CHARSET=gbk;

#修改表的存储引擎
ALTER TABLE ai
	ENGINE=InnoDB;

#展示表的定义语句
SHOW CREATE TABLE ai;